---
title: "figure 4"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
editor_options: 
  chunk_output_type: console
---


```{r}
library(broom)
library(gtsummary)
library(gt)
library(tidyverse)
library(ggpubr)
library(cowplot)
library(gridExtra)
library(readxl)
library(boot)
library(table1)
library(flextable)
library(plyr)
library(Rcpp)
library(modelr)
library(readr)
library(blme)
library(glmnet)
#------------------------------------------------------------import dataset
figure4_data<-  read_excel("~/Projects/S-PRESTO/code/R/Tomer/manuscript figure/input/figure4_data_08122022.xlsx")

#------------------------------------------------------------reformat variables
figure4_data$PEST<- factor(figure4_data$PEST,
                                levels = c('PBA','CIS_DCCA','TRANS_DCCA','PNP','TCP','DMP','DMTP','DMDP','DEP','DETP','DEDP'))

figure4_data$Timepoint<- factor(figure4_data$Timepoint,
                                 levels = c("PCV2","PGV3"))
                                            
figure4_data$covariates<- factor(figure4_data$covariates,
                                 levels = c(
                                            "Ethnicity", 
                                            "Recruitment Age",
                                            "Highest Education",
                                            "Household Income",
                                            "Parity",
                                            "Total Fish",
                                            "Fast food"))

figure4_data$groups<- factor(figure4_data$groups,
                             levels = c('Chinese',
                                        'Indian',
                                        'Malay',
                                        'Below 30',
                                        '30 - 35',
                                        'Above 35',
                                        'University',
                                        'Primary/Secondary/Post Secondary',
                                        '$6,376 and below',
                                        '$6,377 - $11,293',
                                        '$11,294 and above',
                                        '0 previous births',
                                        '>=1 previous births',
                                        "Total Fish",
                                        "Fast food"
                             ))

figure4_data$conf.low<- as.numeric(figure4_data$conf.low)
figure4_data$conf.high<- as.numeric(figure4_data$conf.high)


```

```{r}
figure4<- ggplot(figure4_data,aes(y=groups)) +
  geom_errorbar(aes(xmin = conf.low, xmax = conf.high,color=Timepoint), width = 0.3, size=0.8, position = position_dodge(width = 0.4))+
  geom_point(size=1,aes(x=Estimate,fill=Timepoint),position = position_dodge(width = 0.4)) +
  geom_vline(aes(xintercept=0),linetype="dashed",size=0.5)+
  scale_color_manual(name = "Timepoint", labels = c("Preconception", "Pregnancy"),values = c("#5DADE2", "#3053D0"))+
  scale_fill_manual(guide = 'none',values = c("black", "black"))+
  facet_grid(covariates~PEST, scale="free", space = "free_y")+
  xlab("Regression Coefficient (95% CI)")+
  ylab("Covariates")+
  theme_bw()+
  theme(panel.spacing.y=unit(0.1, "lines"),
        axis.title=element_text(face="bold"),
        strip.background = element_blank(),
        strip.text.x = element_text(colour = "black", face = "bold",size=10),
        strip.text.y = element_text(colour = "black", face = "bold",size=10,angle=0),
        legend.position = "bottom",
        legend.title=element_text(size=10, face="bold",color="black"),
        legend.text=element_text(size=10, face="bold",color="black"))  


figure4






```

