---
title: "figure 2"
output: html_notebook
---


```{r}
library(broom)
library(gtsummary)
library(gt)
library(tidyverse)
library(ggpubr)
library(cowplot)
library(gridExtra)
library(readxl)
library(boot)
library(table1)
library(flextable)
library(plyr)
library(Rcpp)
library(modelr)
library(readr)
library(blme)
library(glmnet)
#------------------------------------------------------------import dataset
figure2_data<-  read_excel("~/Projects/S-PRESTO/code/R/Tomer/manuscript figure/input/7.21.22_figure2_ipw_data.xlsx")

#------------------------------------------------------------reformat variables
figure2_data$PFAS<- factor(figure2_data$PFAS,
                           levels = c("PFOS", "PFOA", "PFHxS", "PFNA", "PFHpA", "PFDA", "PFHpS"))

figure2_data$covariates<- factor(figure2_data$covariates,
                                 levels = c("Ethnicity", 
                                            "Recruitment Age",
                                            "Highest Education",
                                            "Household Income",
                                            "Parity",
                                            "Total Fish",
                                            "Fast food"))

figure2_data$groups<- factor(figure2_data$groups,
                             levels = c('Chinese',
                                        'Indian',
                                        'Malay',
                                        'Below 30',
                                        '30 - 35',
                                        'Above 35',
                                        'University',
                                        'Primary/Secondary/Post Secondary',
                                        '$6,376 and below',
                                        '$6,377 - $11,293',
                                        '$11,294 and above',
                                        '0 previous births',
                                        '>=1 previous births',
                                        'Total Fish',
                                        'Fast food'
                             ))
figure2_data$conf.low<- as.numeric(figure2_data$conf.low)
figure2_data$conf.high<- as.numeric(figure2_data$conf.high)

```

```{r}

figure2<- ggplot(figure2_data,aes(y=groups)) +
  geom_errorbar(aes(xmin = conf.low, xmax = conf.high), width = 0.2,size=1,color="#5DADE2")+
  geom_point(size=1,aes(x=Estimate)) +
  geom_vline(aes(xintercept=0),linetype="dashed",size=0.5)+
  facet_grid(covariates~PFAS, scale="free", space = "free_y")+
  xlab("Regression Coefficient (95% CI)")+
  ylab("Covariates")+
  theme_bw()+
  theme(panel.spacing.y=unit(0.1, "lines"),
        axis.title=element_text(face="bold"),
        strip.background = element_blank(),
        strip.text.x = element_text(colour = "black", face = "bold",size=10),
        strip.text.y = element_text(colour = "black", face = "bold",size=10,angle=0))   


figure2

```

