---
title: "S-PRESTO PFAS determinants Multivariable regression"
author: "Meizhen Yao"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: united
    highlight: tango
    df_print: paged
    fig_caption: yes
    fig_height: 7
    fig_width: 10
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
    self_contained: yes
    code_folding: hide
    toc_depth: 6
header-includes: \usepackage{multirow}
---

<style type="text/css">
body{
  /*font-family: Helvetica;*/
  font-size: 12pt;
}
</style>


```{r setup, include=FALSE}
options(digits = 4)
knitr::opts_chunk$set(echo = TRUE,tidy=TRUE,cache=F,warning = FALSE)
# suppress warning messages for final rendering
old.warn <- getOption("warn")
options(qwraps2_markup = "markdown")

```




```{r, message=FALSE,warning=FALSE}
# load packages
library(broom)
library(gtsummary)
library(gt)
library(tidyverse)
library(ggpubr)
library(cowplot)
library(gridExtra)
library(readxl)
library(boot)
library(table1)
library(flextable)
library(plyr)
library(Rcpp)
library(modelr)
library(readr)
library(gWQS)
library(broom.mixed)
library(yaml)
library(rmarkdown)
library(officer)
library(scales)
library(lme4)

# import data (change the path to the location where you save the dataset)
PFAS<- read_excel("~/Projects/S-PRESTO/input/for paper/chemical_paper/prepared_PFAS_20230316.xlsx")

## log transformation
pest_log <- Pesticides %>% 
            mutate(adjusted_PBA_log=log2(adjusted_PBA), 
                              adjusted_CIS_DCCA_log=log2(adjusted_CIS_DCCA), 
                              adjusted_TRANS_DCCA_log=log2(adjusted_TRANS_DCCA), 
                              adjusted_PNP_log=log2(adjusted_PNP), 
                              adjusted_TCP_log=log2(adjusted_TCP), 
                              adjusted_DMP_log=log2(adjusted_DMP), 
                              adjusted_DMTP_log=log2(adjusted_DMTP), 
                              adjusted_DMDP_log=log2(adjusted_DMDP), 
                              adjusted_DEP_log=log2(adjusted_DEP), 
                              adjusted_DETP_log=log2(adjusted_DETP), 
                              adjusted_DEDP_log=log2(adjusted_DEDP),
            TotalFish_sc = (TotalFish - mean(TotalFish))/sd(TotalFish),
            Fast_food_sc = (Fast_food - mean(Fast_food))/sd(Fast_food))


### covariates
pest_log$ethnicity_specified_recat<- factor(pest_log$ethnicity_specified_recat)

pest_log$pcv1_highest_education_completed_recat<- factor(pest_log$pcv1_highest_education_completed_recat,
                                           levels=c("University","Primary/Secondary/Post_secondary"))

pest_log$pcv1_household_income_recat<- factor(pest_log$pcv1_household_income_recat,
                                           levels=c("$6,376 and below","$6,377 - $11,293","$11,294 and above"))


pest_log$pcv1_parity_recat<- factor(pest_log$pcv1_parity_recat,
                                  levels=c("0",">= 1"))



pest_log$age_at_recruitment_cat <- pest_log$age_at_recruitment
for(i in 1:nrow(pest_log)){
  if(is.na(pest_log$age_at_recruitment[i])==TRUE) {pest_log$age_at_recruitment_cat[i]<- NA}
  else if(pest_log$age_at_recruitment[i] < 30){pest_log$age_at_recruitment_cat[i] <- "30 and below"}
  else if ((pest_log$age_at_recruitment[i] >= 30) & (pest_log$age_at_recruitment[i] < 35)){pest_log$age_at_recruitment_cat[i] <- "30 - 35"}
  else if (pest_log$age_at_recruitment[i] >= 35){pest_log$age_at_recruitment_cat[i] <- "35 and above"}
}
pest_log$age_at_recruitment_cat<- factor(pest_log$age_at_recruitment_cat,
                                           levels=c("30 and below","30 - 35","35 and above"))

PEST<- c('adjusted_PBA_log','adjusted_CIS_DCCA_log','adjusted_TRANS_DCCA_log','adjusted_PNP_log','adjusted_TCP_log','adjusted_DMP_log','adjusted_DMTP_log','adjusted_DMDP_log','adjusted_DEP_log','adjusted_DETP_log','adjusted_DEDP_log')
```

# pesticides
## pcv2
```{r}

pest_log_pcv2<- pest_log %>% 
                filter(Timepoint=="pcv2")

## Fit the models
pest_multireg1_pcv2 <-
  lapply(PEST, function(x){
    temp_pest_multireg1_pcv2 = pest_log[,c(PEST, 'ethnicity_specified_recat' , 'age_at_recruitment_cat' , 'pcv1_highest_education_completed_recat' , 'pcv1_household_income_recat' , 'pcv1_parity_recat','TotalFish_sc','Fast_food_sc')] 
    temp_pest_multireg1_pcv2= temp_pest_multireg1_pcv2[complete.cases(temp_pest_multireg1_pcv2),]
    glm(
      formula = substitute(i ~ ethnicity_specified_recat + age_at_recruitment_cat + pcv1_highest_education_completed_recat + pcv1_household_income_recat +pcv1_parity_recat+TotalFish_sc+Fast_food_sc, 
                           list(i = as.name(x))),
      data = pest_log_pcv2,
      family = gaussian())
  })

## extract coefficients with confidence interval
pest_multireg1_pcv2_coefs <- lapply(pest_multireg1_pcv2, tidy, conf.int = T)
names(pest_multireg1_pcv2_coefs) <- PEST

## combine all lists into one big table
## gives estimates and CI for biomarkers and variables
pest_multireg1_pcv2_coefs_data1 <- bind_rows(pest_multireg1_pcv2_coefs, .id = "PEST")


## subset estimates and CI for _only the biomarkers_
pest_multireg1_pcv2_coefs_data <- pest_multireg1_pcv2_coefs_data1 %>% 
                           select(PEST, term, estimate,  conf.low, conf.high) %>% 
                           mutate(Estimate = round(estimate, 3),
                                  conf.low = round(conf.low, 3),
                                  conf.high = round(conf.high, 3),
                                  Timepoint = "pcv2")

```


## pgv3
```{r}

pest_log_pgv3<- pest_log %>% 
                filter(Timepoint=="pgv3")

## Fit the models
pest_multireg1_pgv3 <-
  lapply(PEST, function(x){
    temp_pest_multireg1_pgv3 = pest_log[,c(PEST, 'ethnicity_specified_recat' , 'age_at_recruitment_cat' , 'pcv1_highest_education_completed_recat' , 'pcv1_household_income_recat' , 'pcv1_parity_recat','TotalFish_sc','Fast_food_sc')] 
    temp_pest_multireg1_pgv3= temp_pest_multireg1_pgv3[complete.cases(temp_pest_multireg1_pgv3),]
    glm(
      formula = substitute(i ~ ethnicity_specified_recat + age_at_recruitment_cat + pcv1_highest_education_completed_recat + pcv1_household_income_recat +pcv1_parity_recat+TotalFish_sc+Fast_food_sc, 
                           list(i = as.name(x))),
      data = pest_log_pgv3,
      family = gaussian())
  })

## extract coefficients with confidence interval
pest_multireg1_pgv3_coefs <- lapply(pest_multireg1_pgv3, tidy, conf.int = T)
names(pest_multireg1_pgv3_coefs) <- PEST

## combine all lists into one big table
## gives estimates and CI for biomarkers and variables
pest_multireg1_pgv3_coefs_data1 <- bind_rows(pest_multireg1_pgv3_coefs, .id = "PEST")


## subset estimates and CI for _only the biomarkers_
pest_multireg1_pgv3_coefs_data <- pest_multireg1_pgv3_coefs_data1 %>% 
                           select(PEST, term, estimate,  conf.low, conf.high) %>% 
                           mutate(Estimate = round(estimate, 3),
                                  conf.low = round(conf.low, 3),
                                  conf.high = round(conf.high, 3),
                                  Timepoint = "pgv3")

```

## combine datasets
```{r}
pest_multireg1_coefs_data<- rbind(pest_multireg1_pcv2_coefs_data, pest_multireg1_pgv3_coefs_data)

write_xlsx(pest_multireg1_coefs_data, "~/Projects/S-PRESTO/code/R/Tomer/manuscript figure/input/figure4_data_raw_08122022.xlsx")
```

