---
title: "S-PRESTO PFAS sensitivity analysis"
author: "Meizhen Yao"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: united
    highlight: tango
    df_print: paged
    fig_caption: yes
    fig_height: 7
    fig_width: 10
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
    self_contained: yes
    code_folding: hide
    toc_depth: 6
header-includes: \usepackage{multirow}

---

<style type="text/css">
body{
  /*font-family: Helvetica;*/
  font-size: 12pt;
}
</style>


```{r setup, include=FALSE}
options(digits = 4)
knitr::opts_chunk$set(echo = TRUE,tidy=TRUE,cache=F,warning = FALSE)
# suppress warning messages for final rendering
old.warn <- getOption("warn")
options(qwraps2_markup = "markdown")

```




```{r, message=FALSE,warning=FALSE}
# load packages
library(broom)
library(gtsummary)
library(gt)
library(tidyverse)
library(ggpubr)
library(cowplot)
library(gridExtra)
library(readxl)
library(boot)
library(table1)
library(flextable)
library(plyr)
library(Rcpp)
library(modelr)
library(readr)
library(gWQS)
library(broom.mixed)
library(yaml)
library(rmarkdown)
library(officer)
library(scales)
library(lme4)
library(mediation)

# import data (change the path to the location where you save the dataset)
PFAS<- read_excel("C:/Users/yaom03/OneDrive - The Mount Sinai Hospital/Projects/S-PRESTO/input/for paper/chemical_paper/prepared_PFAS_20230316.xlsx")

# rosnerTest(PFAS$PFHxS, k=10)
# rosnerTest(PFAS$PFOS_Total, k=10)
# rosnerTest(PFAS$PFOA_Linear, k=10)

## log transformation
PFAS_log <- PFAS %>%  
            mutate(PFHxS_log=log2(PFHxS), 
                   PFOS_Total_log=log2(PFOS_Total), 
                   PFOA_Linear_log=log2(PFOA_Linear), 
                   PFNA_log=log2(PFNA),
            TotalFish_sc = (TotalFish - mean(TotalFish))/sd(TotalFish),
            Fast_food_sc = (Fast_food - mean(Fast_food))/sd(Fast_food),
            fruit_sc = (fruit - mean(fruit))/sd(fruit),
            vegetable_sc = (vegetable - mean(vegetable))/sd(vegetable),
            TotalFish_log = log2(TotalFish+0.1),
            Fast_food_sc = log2(Fast_food+0.1),
            fruit_sc = log2(fruit+0.1),
            vegetable_log = log2(vegetable+0.1),
            vegetable_boil_sc = (vegetable_boil - mean(vegetable_boil))/sd(vegetable_boil),
            vegetable_SF_sc = (vegetable_SF - mean(vegetable_SF))/sd(vegetable_SF),
            Styrofoam_boxes_freq_mean_sc = (Styrofoam_boxes_freq_mean - mean(Styrofoam_boxes_freq_mean))/sd(Styrofoam_boxes_freq_mean),
            Plastic_boxes_freq_mean_sc = (Plastic_boxes_freq_mean - mean(Plastic_boxes_freq_mean))/sd(Plastic_boxes_freq_mean),
            ethnicity_specified_recat_bi = ifelse(ethnicity_specified_recat == "Chinese", "Chinese", "Malay/Indian"))

## numeric
PFAS_log$PFHpA_bi<- PFAS_log$PFHpA_Comment
for(i in 1:nrow(PFAS_log)){
  if ( PFAS_log$PFHpA_Comment[i]==37){PFAS_log$PFHpA_bi[i]<-0}
  else if (PFAS_log$PFHpA_Comment[i]==0){PFAS_log$PFHpA_bi[i]<-1}
}

PFAS_log$PFHpA_bi<- factor(PFAS_log$PFHpA_bi,
                           levels = c(0,1))

PFAS_log$PFDA_bi<- PFAS_log$PFDA_Comment
for(i in 1:nrow(PFAS_log)){
  if ( PFAS_log$PFDA_Comment[i]==37){PFAS_log$PFDA_bi[i]<-0}
  else if (PFAS_log$PFDA_Comment[i]==0){PFAS_log$PFDA_bi[i]<-1}
}

PFAS_log$PFDA_bi<- factor(PFAS_log$PFDA_bi,
                          levels = c(0,1))

PFAS_log$PFHpS_bi<- PFAS_log$PFHpS_Comment
for(i in 1:nrow(PFAS_log)){
  if ( PFAS_log$PFHpS_Comment[i]==37){PFAS_log$PFHpS_bi[i]<-0}
  else if (PFAS_log$PFHpS_Comment[i]==0){PFAS_log$PFHpS_bi[i]<-1}
}

PFAS_log$PFHpS_bi<- factor(PFAS_log$PFHpS_bi,
                           levels = c(0,1))

## covariates
PFAS_log$ethnicity_specified_recat<- factor(PFAS_log$ethnicity_specified_recat,
                                            levels = c("Chinese","Malay","Indian"))

PFAS_log$pcv1_highest_education_completed_recat<- factor(PFAS_log$pcv1_highest_education_completed_recat,
                                           levels=c("University","Primary/Secondary/Post_secondary"))

PFAS_log$pcv1_household_income_recat<- factor(PFAS_log$pcv1_household_income_recat,
                                           levels=c("$6,376 and below","$6,377 - $11,293","$11,294 and above"))


PFAS_log$pcv1_parity_recat<- factor(PFAS_log$pcv1_parity_recat,
                                  levels=c("0",">= 1"))



PFAS_log$age_at_recruitment_cat <- factor(PFAS_log$age_at_recruitment_cat,
                                           levels=c("Age first tertile","Age second tertile","Age third tertile"))


PFAS_log$Styrofoam_boxes<- factor(PFAS_log$Styrofoam_boxes,
                                        levels = c("No", "Yes"))
PFAS_log$Plastic_boxes<- factor(PFAS_log$Plastic_boxes,
                                        levels = c("No", "Yes"))



PFAS_log$occupation<- factor(PFAS_log$occupation,
                            levels = c("Not working", "Office worker", "Health care worker", "Service worker"))

# 
# q_age<- quantile(PFAS_log$mca_dim1, probs = c(1/3, 2/3), type=2)
# PFAS_log$mca_dim1_cat <- PFAS_log$mca_dim1
# for(i in 1:nrow(PFAS_log)){
#   if(is.na(PFAS_log$mca_dim1[i])==TRUE) {PFAS_log$mca_dim1_cat[i]<- NA}
#   else if(PFAS_log$mca_dim1[i] <= q_age[1]){PFAS_log$mca_dim1_cat[i] <- "Low-tendency-outside"}
#   else if ((PFAS_log$mca_dim1[i] > q_age[1]) & (PFAS_log$mca_dim1[i] <= q_age[2])){PFAS_log$mca_dim1_cat[i] <- "Mid-tendency-outside"}
#   else if (PFAS_log$mca_dim1[i] > q_age[2]){PFAS_log$mca_dim1_cat[i] <- "High-tendency-outside"}
# }
# PFAS_log$mca_dim1_cat<- factor(PFAS_log$mca_dim1_cat,
#                                levels=c("Low-tendency-outside","Mid-tendency-outside","High-tendency-outside"))
# 
# 
# q_age<- quantile(PFAS_log$mca_dim2, probs = c(1/3, 2/3), type=2)
# PFAS_log$mca_dim2_cat <- PFAS_log$mca_dim2
# for(i in 1:nrow(PFAS_log)){
#   if(is.na(PFAS_log$mca_dim2[i])==TRUE) {PFAS_log$mca_dim2_cat[i]<- NA}
#   else if(PFAS_log$mca_dim2[i] <= q_age[1]){PFAS_log$mca_dim2_cat[i] <- "Low-tendency-packaging"}
#   else if ((PFAS_log$mca_dim2[i] > q_age[1]) & (PFAS_log$mca_dim2[i] <= q_age[2])){PFAS_log$mca_dim2_cat[i] <- "Mid-tendency-packaging"}
#   else if (PFAS_log$mca_dim2[i] > q_age[2]){PFAS_log$mca_dim2_cat[i] <- "High-tendency-packaging"}
# }
# PFAS_log$mca_dim2_cat<- factor(PFAS_log$mca_dim2_cat,
#                                levels=c("Low-tendency-packaging","Mid-tendency-packaging","High-tendency-packaging"))

q_age<- quantile(PFAS_log$mca_dim1, probs = c(1/2), type=2)
PFAS_log$mca_dim1_cat <- PFAS_log$mca_dim1
for(i in 1:nrow(PFAS_log)){
  if(is.na(PFAS_log$mca_dim1[i])==TRUE) {PFAS_log$mca_dim1_cat[i]<- NA}
  else if(PFAS_log$mca_dim1[i] < q_age[1]){PFAS_log$mca_dim1_cat[i] <- "Low-tendency-outside"}
  else if (PFAS_log$mca_dim1[i] >= q_age[1]){PFAS_log$mca_dim1_cat[i] <- "High-tendency-outside"}
}
PFAS_log$mca_dim1_cat<- factor(PFAS_log$mca_dim1_cat,
                               levels=c("Low-tendency-outside","High-tendency-outside"))


q_age<- quantile(PFAS_log$mca_dim2, probs = c(1/2), type=2)
PFAS_log$mca_dim2_cat <- PFAS_log$mca_dim2
for(i in 1:nrow(PFAS_log)){
  if(is.na(PFAS_log$mca_dim2[i])==TRUE) {PFAS_log$mca_dim2_cat[i]<- NA}
  else if(PFAS_log$mca_dim2[i] < q_age[1]){PFAS_log$mca_dim2_cat[i] <- "Low-tendency-packaging"}
  else if (PFAS_log$mca_dim2[i] >= q_age[1]){PFAS_log$mca_dim2_cat[i] <- "High-tendency-packaging"}
}
PFAS_log$mca_dim2_cat<- factor(PFAS_log$mca_dim2_cat,
                               levels=c("Low-tendency-packaging","High-tendency-packaging"))



## PFAS information
PFAS_cont<- c('PFOS_Total_log', 'PFOA_Linear_log', 'PFNA_log', 'PFHxS_log')

PFAS_bi<- c('PFDA_bi', 'PFHpA_bi', 'PFHpS_bi')

PFAS_name<- c('PFOS_Total_log', 'PFOA_Linear_log', 'PFNA_log', 'PFHxS_log', 'PFDA_bi', 'PFHpA_bi', 'PFHpS_bi')

beta<- c('beta', 'beta', 'beta', 'beta', 'log(OR)', 'log(OR)', 'log(OR)')
PFAS_info<- data.frame(PFAS_name, 
                       beta)

tbl_summary(PFAS_log,
            include = c(ethnicity_specified_recat, age_at_recruitment_cat, pcv1_highest_education_completed_recat, pcv1_household_income_recat, pcv1_parity_recat, 
         Styrofoam_boxes,Plastic_boxes,
         occupation)) %>% 
   bold_labels()

```


```{r}
tbl_summary(PFAS_log,
            include = c(ethnicity_specified_recat, Fast_food_sc, age_at_recruitment_cat, pcv1_highest_education_completed_recat, pcv1_household_income_recat, occupation, fruit_sc, mca_dim1_cat, mca_dim2_cat, Fast_food),
            by = ethnicity_specified_recat) %>% 
   bold_labels() %>% 
   add_p()

tbl_summary(PFAS_log,
            include = c(mca_dim1, mca_dim2),
            by = ethnicity_specified_recat) %>% 
   bold_labels() %>% 
   add_p()

tbl_summary(PFAS_log,
            include = c(mca_dim2_cat, Fast_food),
            by = mca_dim2_cat,
            statistic = list(all_continuous() ~ "{median} ({p25}, {p75})")) %>% 
   bold_labels() %>% 
   add_p()


tbl_summary(PFAS_log,
            include = c(mca_dim1_cat, Fast_food),
            by = mca_dim1_cat) %>% 
   bold_labels() %>% 
   add_p()


cor(PFAS_log$Fast_food, PFAS_log$mca_dim2)

tbl_summary(PFAS_log,
            include = c(mca_dim1_cat),
            by = mca_dim2_cat) %>% 
   bold_labels() %>% 
   add_p()



```


# By ethnicity
## model1: sociodemographic factors
```{r, message=FALSE,warning=FALSE}

PFAS_log_chinese<- PFAS_log %>%
                   filter(ethnicity_specified_recat_bi == "Chinese")

## Fit the models
PFAS_multireg1 <-
   c(lapply(PFAS_cont, function(x){
    
    glm(formula = substitute(i ~ age_at_recruitment_cat + pcv1_highest_education_completed_recat + pcv1_household_income_recat + occupation, 
                           list(i = as.name(x))),
      data = PFAS_log_chinese,
      family = gaussian())
    }),
  lapply(PFAS_bi, function(x){
    
    glm(formula = substitute(i ~ age_at_recruitment_cat + pcv1_highest_education_completed_recat + pcv1_household_income_recat + occupation, 
                           list(i = as.name(x))),
      data = PFAS_log_chinese,
      family = binomial())
   }))

## extract coefficients with confidence interval
PFAS_multireg1_coefs <- lapply(PFAS_multireg1, tidy, conf.int = T)
names(PFAS_multireg1_coefs) <- PFAS_name

## combine all lists into one big table
## gives estimates and CI for biomarkers and variables
PFAS_multireg1_coefs_data1 <- bind_rows(PFAS_multireg1_coefs, .id = "PFAS_name")


## subset estimates and CI for _only the biomarkers_
PFAS_multireg1_coefs_data <- PFAS_multireg1_coefs_data1 %>% 
                           filter(term != "(Intercept)" & term !=  "sd__(Intercept)" & term !=  "sd__Observation") %>% 
                           mutate(Estimate = round(estimate, 3),
                                  conf.low = round(conf.low, 3),
                                  conf.high = round(conf.high, 3)) %>% 
                           dplyr::select(PFAS_name, term, Estimate, conf.low, conf.high) 

PFAS_multireg1_coefs_data$sig<- ifelse(PFAS_multireg1_coefs_data$conf.low >0 & PFAS_multireg1_coefs_data$conf.high >0 | PFAS_multireg1_coefs_data$conf.low <0 & PFAS_multireg1_coefs_data$conf.high <0, "*", NA )

model1<- PFAS_multireg1_coefs_data %>% 
                            inner_join(PFAS_info, by="PFAS_name")%>% 
                            mutate(Estimate = if_else(beta=="log(OR)", exp(Estimate), Estimate),
                                   conf.low = if_else(beta=="log(OR)", exp(conf.low), conf.low),
                                   conf.high = if_else(beta=="log(OR)", exp(conf.high), conf.high))

## put result into one table
tabel<- flextable(as_grouped_data(model1, groups = "PFAS_name")) %>%          
        color(~sig == "*", ~conf.low, color = "red")%>% 
        color(~sig == "*", ~conf.high, color = "red")%>%
        theme_box() 
        

tabel


######## extract results
education_chinese<- model1 %>% 
                    filter(term == "pcv1_highest_education_completed_recatPrimary/Secondary/Post_secondary") %>% 
                    mutate(ethnicity = "Chinese")


```



```{r, message=FALSE,warning=FALSE}

PFAS_log_chinese<- PFAS_log %>%
                   filter(ethnicity_specified_recat_bi != "Chinese")

## Fit the models
PFAS_multireg1 <-
   c(lapply(PFAS_cont, function(x){
    
    glm(formula = substitute(i ~ age_at_recruitment_cat + pcv1_highest_education_completed_recat + pcv1_household_income_recat + occupation, 
                           list(i = as.name(x))),
      data = PFAS_log_chinese,
      family = gaussian())
    }),
  lapply(PFAS_bi, function(x){
    
    glm(formula = substitute(i ~ age_at_recruitment_cat + pcv1_highest_education_completed_recat + pcv1_household_income_recat + occupation, 
                           list(i = as.name(x))),
      data = PFAS_log_chinese,
      family = binomial())
   }))

## extract coefficients with confidence interval
PFAS_multireg1_coefs <- lapply(PFAS_multireg1, tidy, conf.int = T)
names(PFAS_multireg1_coefs) <- PFAS_name

## combine all lists into one big table
## gives estimates and CI for biomarkers and variables
PFAS_multireg1_coefs_data1 <- bind_rows(PFAS_multireg1_coefs, .id = "PFAS_name")


## subset estimates and CI for _only the biomarkers_
PFAS_multireg1_coefs_data <- PFAS_multireg1_coefs_data1 %>% 
                           filter(term != "(Intercept)" & term !=  "sd__(Intercept)" & term !=  "sd__Observation") %>% 
                           mutate(Estimate = round(estimate, 3),
                                  conf.low = round(conf.low, 3),
                                  conf.high = round(conf.high, 3)) %>% 
                           dplyr::select(PFAS_name, term, Estimate, conf.low, conf.high) 

PFAS_multireg1_coefs_data$sig<- ifelse(PFAS_multireg1_coefs_data$conf.low >0 & PFAS_multireg1_coefs_data$conf.high >0 | PFAS_multireg1_coefs_data$conf.low <0 & PFAS_multireg1_coefs_data$conf.high <0, "*", NA )

model1<- PFAS_multireg1_coefs_data %>% 
                            inner_join(PFAS_info, by="PFAS_name")%>% 
                            mutate(Estimate = if_else(beta=="log(OR)", exp(Estimate), Estimate),
                                   conf.low = if_else(beta=="log(OR)", exp(conf.low), conf.low),
                                   conf.high = if_else(beta=="log(OR)", exp(conf.high), conf.high))

## put result into one table
tabel<- flextable(as_grouped_data(model1, groups = "PFAS_name")) %>%          
        color(~sig == "*", ~conf.low, color = "red")%>% 
        color(~sig == "*", ~conf.high, color = "red")%>%
        theme_box() 
        

tabel

######## extract results
education_nochinese<- model1 %>% 
                    filter(term == "pcv1_highest_education_completed_recatPrimary/Secondary/Post_secondary") %>% 
                    mutate(ethnicity = "Malay/Indian")


```


```{r, message=FALSE,warning=FALSE}

## Fit the models
PFAS_multireg1 <-
   c(lapply(PFAS_cont, function(x){
    
    glm(formula = substitute(i ~ age_at_recruitment_cat + pcv1_highest_education_completed_recat*ethnicity_specified_recat_bi + pcv1_household_income_recat + occupation, 
                           list(i = as.name(x))),
      data = PFAS_log,
      family = gaussian())
    }),
  lapply(PFAS_bi, function(x){
    
    glm(formula = substitute(i ~ age_at_recruitment_cat + pcv1_highest_education_completed_recat*ethnicity_specified_recat_bi + pcv1_household_income_recat + occupation, 
                           list(i = as.name(x))),
      data = PFAS_log,
      family = binomial())
   }))

## extract coefficients with confidence interval
PFAS_multireg1_coefs <- lapply(PFAS_multireg1, tidy, conf.int = T)
names(PFAS_multireg1_coefs) <- PFAS_name

## combine all lists into one big table
## gives estimates and CI for biomarkers and variables
PFAS_multireg1_coefs_data1 <- bind_rows(PFAS_multireg1_coefs, .id = "PFAS_name")


## subset estimates and CI for _only the biomarkers_
PFAS_multireg1_coefs_data <- PFAS_multireg1_coefs_data1 %>% 
                           filter(term != "(Intercept)" & term !=  "sd__(Intercept)" & term !=  "sd__Observation") %>% 
                           mutate(Estimate = round(estimate, 3),
                                  conf.low = round(conf.low, 3),
                                  conf.high = round(conf.high, 3),
                                  p.value = round(p.value, 5)) %>% 
                           dplyr::select(PFAS_name, term, Estimate, p.value) 


## put result into one table
tabel<- flextable(as_grouped_data(PFAS_multireg1_coefs_data, groups = "PFAS_name")) %>%          
        color(~p.value < 0.05, ~p.value, color = "red")%>% 
        theme_box() 
        

tabel



```


## model2: fast food intake
```{r, message=FALSE,warning=FALSE}

PFAS_log_chinese<- PFAS_log %>%
                   filter(ethnicity_specified_recat_bi == "Chinese")

## Fit the models
PFAS_multireg1 <-
   c(lapply(PFAS_cont, function(x){
    
    glm(formula = substitute(i ~ Fast_food_sc + age_at_recruitment_cat + pcv1_highest_education_completed_recat + pcv1_household_income_recat + occupation, 
                           list(i = as.name(x))),
      data = PFAS_log_chinese,
      family = gaussian())
    }),
  lapply(PFAS_bi, function(x){
    
    glm(formula = substitute(i ~ Fast_food_sc + age_at_recruitment_cat + pcv1_highest_education_completed_recat + pcv1_household_income_recat + occupation, 
                           list(i = as.name(x))),
      data = PFAS_log_chinese,
      family = binomial())
   }))

## extract coefficients with confidence interval
PFAS_multireg1_coefs <- lapply(PFAS_multireg1, tidy, conf.int = T)
names(PFAS_multireg1_coefs) <- PFAS_name

## combine all lists into one big table
## gives estimates and CI for biomarkers and variables
PFAS_multireg1_coefs_data1 <- bind_rows(PFAS_multireg1_coefs, .id = "PFAS_name")


## subset estimates and CI for _only the biomarkers_
PFAS_multireg1_coefs_data <- PFAS_multireg1_coefs_data1 %>% 
                           filter(term != "(Intercept)" & term !=  "sd__(Intercept)" & term !=  "sd__Observation") %>% 
                           mutate(Estimate = round(estimate, 3),
                                  conf.low = round(conf.low, 3),
                                  conf.high = round(conf.high, 3)) %>% 
                           dplyr::select(PFAS_name, term, Estimate, conf.low, conf.high) 

PFAS_multireg1_coefs_data$sig<- ifelse(PFAS_multireg1_coefs_data$conf.low >0 & PFAS_multireg1_coefs_data$conf.high >0 | PFAS_multireg1_coefs_data$conf.low <0 & PFAS_multireg1_coefs_data$conf.high <0, "*", NA )

model1<- PFAS_multireg1_coefs_data %>% 
                            inner_join(PFAS_info, by="PFAS_name")%>% 
                            mutate(Estimate = if_else(beta=="log(OR)", exp(Estimate), Estimate),
                                   conf.low = if_else(beta=="log(OR)", exp(conf.low), conf.low),
                                   conf.high = if_else(beta=="log(OR)", exp(conf.high), conf.high))

## put result into one table
tabel<- flextable(as_grouped_data(model1, groups = "PFAS_name")) %>%          
        color(~sig == "*", ~conf.low, color = "red")%>% 
        color(~sig == "*", ~conf.high, color = "red")%>%
        theme_box() 
        

tabel

fastfood_chinese<- model1 %>% 
                    filter(term == "Fast_food_sc") %>% 
                    mutate(ethnicity = "Chinese")

```



```{r, message=FALSE,warning=FALSE}

PFAS_log_chinese<- PFAS_log %>%
                   filter(ethnicity_specified_recat_bi != "Chinese")

## Fit the models
PFAS_multireg1 <-
   c(lapply(PFAS_cont, function(x){
    
    glm(formula = substitute(i ~ Fast_food_sc + age_at_recruitment_cat + pcv1_highest_education_completed_recat + pcv1_household_income_recat + occupation, 
                           list(i = as.name(x))),
      data = PFAS_log_chinese,
      family = gaussian())
    }),
  lapply(PFAS_bi, function(x){
    
    glm(formula = substitute(i ~ Fast_food_sc + age_at_recruitment_cat + pcv1_highest_education_completed_recat + pcv1_household_income_recat + occupation, 
                           list(i = as.name(x))),
      data = PFAS_log_chinese,
      family = binomial())
   }))

## extract coefficients with confidence interval
PFAS_multireg1_coefs <- lapply(PFAS_multireg1, tidy, conf.int = T)
names(PFAS_multireg1_coefs) <- PFAS_name

## combine all lists into one big table
## gives estimates and CI for biomarkers and variables
PFAS_multireg1_coefs_data1 <- bind_rows(PFAS_multireg1_coefs, .id = "PFAS_name")


## subset estimates and CI for _only the biomarkers_
PFAS_multireg1_coefs_data <- PFAS_multireg1_coefs_data1 %>% 
                           filter(term != "(Intercept)" & term !=  "sd__(Intercept)" & term !=  "sd__Observation") %>% 
                           mutate(Estimate = round(estimate, 3),
                                  conf.low = round(conf.low, 3),
                                  conf.high = round(conf.high, 3)) %>% 
                           dplyr::select(PFAS_name, term, Estimate, conf.low, conf.high) 

PFAS_multireg1_coefs_data$sig<- ifelse(PFAS_multireg1_coefs_data$conf.low >0 & PFAS_multireg1_coefs_data$conf.high >0 | PFAS_multireg1_coefs_data$conf.low <0 & PFAS_multireg1_coefs_data$conf.high <0, "*", NA )

model1<- PFAS_multireg1_coefs_data %>% 
                            inner_join(PFAS_info, by="PFAS_name")%>% 
                            mutate(Estimate = if_else(beta=="log(OR)", exp(Estimate), Estimate),
                                   conf.low = if_else(beta=="log(OR)", exp(conf.low), conf.low),
                                   conf.high = if_else(beta=="log(OR)", exp(conf.high), conf.high))

## put result into one table
tabel<- flextable(as_grouped_data(model1, groups = "PFAS_name")) %>%          
        color(~sig == "*", ~conf.low, color = "red")%>% 
        color(~sig == "*", ~conf.high, color = "red")%>%
        theme_box() 
        

tabel

fastfood_nochinese<- model1 %>% 
                    filter(term == "Fast_food_sc") %>% 
                    mutate(ethnicity = "Malay/Indian")

```


```{r, message=FALSE,warning=FALSE}

## Fit the models
PFAS_multireg1 <-
   c(lapply(PFAS_cont, function(x){
    
    glm(formula = substitute(i ~ Fast_food_sc*ethnicity_specified_recat_bi + age_at_recruitment_cat + pcv1_highest_education_completed_recat + pcv1_household_income_recat + occupation, 
                           list(i = as.name(x))),
      data = PFAS_log,
      family = gaussian())
    }),
  lapply(PFAS_bi, function(x){
    
    glm(formula = substitute(i ~ Fast_food_sc*ethnicity_specified_recat_bi + age_at_recruitment_cat + pcv1_highest_education_completed_recat + pcv1_household_income_recat + occupation, 
                           list(i = as.name(x))),
      data = PFAS_log,
      family = binomial())
   }))

## extract coefficients with confidence interval
PFAS_multireg1_coefs <- lapply(PFAS_multireg1, tidy, conf.int = T)
names(PFAS_multireg1_coefs) <- PFAS_name

## combine all lists into one big table
## gives estimates and CI for biomarkers and variables
PFAS_multireg1_coefs_data1 <- bind_rows(PFAS_multireg1_coefs, .id = "PFAS_name")


## subset estimates and CI for _only the biomarkers_
PFAS_multireg1_coefs_data <- PFAS_multireg1_coefs_data1 %>% 
                           filter(term != "(Intercept)" & term !=  "sd__(Intercept)" & term !=  "sd__Observation") %>% 
                           mutate(Estimate = round(estimate, 3),
                                  conf.low = round(conf.low, 3),
                                  conf.high = round(conf.high, 3),
                                  p.value = round(p.value, 3)) %>% 
                           dplyr::select(PFAS_name, term, Estimate, conf.low, conf.high, p.value) 


## put result into one table
tabel<- flextable(as_grouped_data(PFAS_multireg1_coefs_data, groups = "PFAS_name")) %>%          
        color(~p.value < 0.05, ~p.value, color = "red")%>% 
        theme_box() 
        

tabel



```


```{r}
model<- rbind(education_chinese,
                   education_nochinese,
                   fastfood_chinese,
                   fastfood_nochinese)



##### extract results
write_csv(model, "C:/Users/yaom03/OneDrive - The Mount Sinai Hospital/Projects/S-PRESTO/code/R/chemical & covariates/plot_data/PFAS_ethi_strata.csv")

```



# By ethnicity and MCA 
```{r, message=FALSE,warning=FALSE}
PFAS_log_chinese<- PFAS_log %>%
                   filter(mca_dim2_cat == "Low-tendency-packaging")
## Fit the models
PFAS_multireg1 <-
   c(lapply(PFAS_cont, function(x){
    
    glm(formula = substitute(i ~ Fast_food_sc + ethnicity_specified_recat + age_at_recruitment_cat + pcv1_highest_education_completed_recat + pcv1_household_income_recat + occupation, 
                           list(i = as.name(x))),
      data = PFAS_log_chinese,
      family = gaussian())
    }),
  lapply(PFAS_bi, function(x){
    
    glm(formula = substitute(i ~ Fast_food_sc + ethnicity_specified_recat + age_at_recruitment_cat + pcv1_highest_education_completed_recat + pcv1_household_income_recat + occupation, 
                           list(i = as.name(x))),
      data = PFAS_log_chinese,
      family = binomial())
   }))

## extract coefficients with confidence interval
PFAS_multireg1_coefs <- lapply(PFAS_multireg1, tidy, conf.int = T)
names(PFAS_multireg1_coefs) <- PFAS_name

## combine all lists into one big table
## gives estimates and CI for biomarkers and variables
PFAS_multireg1_coefs_data1 <- bind_rows(PFAS_multireg1_coefs, .id = "PFAS_name")




## subset estimates and CI for _only the biomarkers_
PFAS_multireg1_coefs_data <- PFAS_multireg1_coefs_data1 %>% 
                    filter(term == "Fast_food_sc") %>% 
                           filter(term != "(Intercept)" & term !=  "sd__(Intercept)" & term !=  "sd__Observation") %>% 
                           mutate(Estimate = round(estimate, 3),
                                  conf.low = round(conf.low, 3),
                                  conf.high = round(conf.high, 3)) %>% 
                           dplyr::select(PFAS_name, term, Estimate, conf.low, conf.high) 

PFAS_multireg1_coefs_data$sig<- ifelse(PFAS_multireg1_coefs_data$conf.low >0 & PFAS_multireg1_coefs_data$conf.high >0 | PFAS_multireg1_coefs_data$conf.low <0 & PFAS_multireg1_coefs_data$conf.high <0, "*", NA )

model1<- PFAS_multireg1_coefs_data %>% 
                            inner_join(PFAS_info, by="PFAS_name")%>% 
                            mutate(Estimate = if_else(beta=="log(OR)", exp(Estimate), Estimate),
                                   conf.low = if_else(beta=="log(OR)", exp(conf.low), conf.low),
                                   conf.high = if_else(beta=="log(OR)", exp(conf.high), conf.high))

## put result into one table
tabel<- flextable(as_grouped_data(model1, groups = "PFAS_name")) %>%          
        color(~sig == "*", ~conf.low, color = "red")%>% 
        color(~sig == "*", ~conf.high, color = "red")%>%
        theme_box() 
        

tabel

fastfood_low<- model1 %>% 
               mutate(package = "Low-tendency-packaging")




```

```{r, message=FALSE,warning=FALSE}
PFAS_log_chinese<- PFAS_log %>%
                   filter(mca_dim2_cat == "High-tendency-packaging")
## Fit the models
PFAS_multireg1 <-
   c(lapply(PFAS_cont, function(x){
    
    glm(formula = substitute(i ~ Fast_food_sc + ethnicity_specified_recat + age_at_recruitment_cat + pcv1_highest_education_completed_recat + pcv1_household_income_recat + occupation, 
                           list(i = as.name(x))),
      data = PFAS_log_chinese,
      family = gaussian())
    }),
  lapply(PFAS_bi, function(x){
    
    glm(formula = substitute(i ~ Fast_food_sc + ethnicity_specified_recat + age_at_recruitment_cat + pcv1_highest_education_completed_recat + pcv1_household_income_recat + occupation, 
                           list(i = as.name(x))),
      data = PFAS_log_chinese,
      family = binomial())
   }))

## extract coefficients with confidence interval
PFAS_multireg1_coefs <- lapply(PFAS_multireg1, tidy, conf.int = T)
names(PFAS_multireg1_coefs) <- PFAS_name

## combine all lists into one big table
## gives estimates and CI for biomarkers and variables
PFAS_multireg1_coefs_data1 <- bind_rows(PFAS_multireg1_coefs, .id = "PFAS_name")


## subset estimates and CI for _only the biomarkers_
PFAS_multireg1_coefs_data <- PFAS_multireg1_coefs_data1 %>% 
                    filter(term == "Fast_food_sc") %>% 
                           filter(term != "(Intercept)" & term !=  "sd__(Intercept)" & term !=  "sd__Observation") %>% 
                           mutate(Estimate = round(estimate, 3),
                                  conf.low = round(conf.low, 3),
                                  conf.high = round(conf.high, 3)) %>% 
                           dplyr::select(PFAS_name, term, Estimate, conf.low, conf.high) 

PFAS_multireg1_coefs_data$sig<- ifelse(PFAS_multireg1_coefs_data$conf.low >0 & PFAS_multireg1_coefs_data$conf.high >0 | PFAS_multireg1_coefs_data$conf.low <0 & PFAS_multireg1_coefs_data$conf.high <0, "*", NA )

model1<- PFAS_multireg1_coefs_data %>% 
                            inner_join(PFAS_info, by="PFAS_name")%>% 
                            mutate(Estimate = if_else(beta=="log(OR)", exp(Estimate), Estimate),
                                   conf.low = if_else(beta=="log(OR)", exp(conf.low), conf.low),
                                   conf.high = if_else(beta=="log(OR)", exp(conf.high), conf.high))

## put result into one table
tabel<- flextable(as_grouped_data(model1, groups = "PFAS_name")) %>%          
        color(~sig == "*", ~conf.low, color = "red")%>% 
        color(~sig == "*", ~conf.high, color = "red")%>%
        theme_box() 
        

tabel


fastfood_high<- model1 %>% 
                    filter(term == "Fast_food_sc") %>% 
                    mutate(package = "High-tendency-packaging")


```


```{r}
model<- rbind(fastfood_low,
                   fastfood_high)



##### extract results
write_csv(model, "C:/Users/yaom03/OneDrive - The Mount Sinai Hospital/Projects/S-PRESTO/code/R/chemical & covariates/plot_data/PFAS_mca_strata.csv")

```




```{r, message=FALSE,warning=FALSE}

## Fit the models
PFAS_multireg1 <-
   c(lapply(PFAS_cont, function(x){
    
    glm(formula = substitute(i ~ Fast_food_sc*mca_dim2_cat + ethnicity_specified_recat + age_at_recruitment_cat + pcv1_highest_education_completed_recat + pcv1_household_income_recat + occupation, 
                           list(i = as.name(x))),
      data = PFAS_log,
      family = gaussian())
    }),
  lapply(PFAS_bi, function(x){
    
    glm(formula = substitute(i ~ Fast_food_sc*mca_dim2_cat + ethnicity_specified_recat + age_at_recruitment_cat + pcv1_highest_education_completed_recat + pcv1_household_income_recat + occupation, 
                           list(i = as.name(x))),
      data = PFAS_log,
      family = binomial())
   }))

## extract coefficients with confidence interval
PFAS_multireg1_coefs <- lapply(PFAS_multireg1, tidy, conf.int = T)
names(PFAS_multireg1_coefs) <- PFAS_name

## combine all lists into one big table
## gives estimates and CI for biomarkers and variables
PFAS_multireg1_coefs_data1 <- bind_rows(PFAS_multireg1_coefs, .id = "PFAS_name")


## subset estimates and CI for _only the biomarkers_
PFAS_multireg1_coefs_data <- PFAS_multireg1_coefs_data1 %>% 
                           filter(term != "(Intercept)" & term !=  "sd__(Intercept)" & term !=  "sd__Observation") %>% 
                           mutate(Estimate = round(estimate, 3),
                                  conf.low = round(conf.low, 3),
                                  conf.high = round(conf.high, 3)) %>% 
                           dplyr::select(PFAS_name, term, Estimate, conf.low, conf.high) 

PFAS_multireg1_coefs_data$sig<- ifelse(PFAS_multireg1_coefs_data$conf.low >0 & PFAS_multireg1_coefs_data$conf.high >0 | PFAS_multireg1_coefs_data$conf.low <0 & PFAS_multireg1_coefs_data$conf.high <0, "*", NA )

model1<- PFAS_multireg1_coefs_data %>% 
                            inner_join(PFAS_info, by="PFAS_name")%>% 
                            mutate(Estimate = if_else(beta=="log(OR)", exp(Estimate), Estimate),
                                   conf.low = if_else(beta=="log(OR)", exp(conf.low), conf.low),
                                   conf.high = if_else(beta=="log(OR)", exp(conf.high), conf.high))

## put result into one table
tabel<- flextable(as_grouped_data(model1, groups = "PFAS_name")) %>%          
        color(~sig == "*", ~conf.low, color = "red")%>% 
        color(~sig == "*", ~conf.high, color = "red")%>%
        theme_box() 
        

tabel


fastfood_high<- model1 %>% 
                    filter(term == "Fast_food_sc") %>% 
                    mutate(package == "High-tendency-packaging")


```



```{r}

# PFAS_log <- PFAS_log[complete.cases(PFAS_log[, c('Fast_food_sc' , 'ethnicity_specified_recat' , 'age_at_recruitment_cat', 'pcv1_highest_education_completed_recat', 'pcv1_household_income_recat', 'occupation', 'PFNA_log', 'mca_dim2_cat')]), ]

# Fit mediator model
med.fit <- glm(mca_dim2_cat ~ Fast_food_sc ,
               data = PFAS_log,
               family = binomial(probit))

# Fit outcome model
out.fit <- glm(PFNA_log ~ mca_dim2_cat + Fast_food_sc ,
               data = PFAS_log,
               family = gaussian())

summary(med.fit)
summary(out.fit)


# Run mediation analysis
med.out <- mediate(med.fit, out.fit, treat = "Fast_food_sc", mediator = "mca_dim2_cat", boot = FALSE)  # Increase sims for stability
summary(med.out)

```














